spring:
  application:
    name: eureka-server
server:
  port: 10001
eureka:
  server:
    wait-time-in-ms-when-sync-empty: 10000 # 设置如果Eureka Server启动时无法从临近Eureka Server节点获取注册信息，它多久不对外提供注册服务
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000  #Eureka Server会定时(默认值为0，默认情况不删除实例）进行检查，如果发现实例在在一定时间（此值由eureka.instance.lease-expiration-duration-in-seconds定义，默认值为90s）内没有收到心跳，则会注销此实例。
    # renewal-percent-threshold: 0.85  # 自我保护系数 当enable-self-preservation: true 时开启
  client:
    fetch-registry: false  # 表示是否从eureka服务器获取注册信息
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka/
  instance:
    lease-expiration-duration-in-seconds: 90